// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class AccessContextManagerRetry: AccessContextManagerStub {
    let inner: any AccessContextManagerStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any AccessContextManagerStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAccessPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse
          in
          return try await self.inner.listAccessPolicies(request: r, options: o)
        })
    }

    public func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.AccessPolicy
          in
          return try await self.inner.getAccessPolicy(request: r, options: o)
        })
    }

    public func createAccessPolicy(
      request: AccessPolicy, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AccessPolicy, o: GoogleGax.RequestOptions) async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAccessPolicy(request: r, options: o)
        })
    }

    public func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAccessPolicy(request: r, options: o)
        })
    }

    public func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAccessPolicy(request: r, options: o)
        })
    }

    public func listAccessLevels(
      request: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAccessLevelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse
          in
          return try await self.inner.listAccessLevels(request: r, options: o)
        })
    }

    public func getAccessLevel(
      request: GetAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAccessLevelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.AccessLevel
          in
          return try await self.inner.getAccessLevel(request: r, options: o)
        })
    }

    public func createAccessLevel(
      request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAccessLevelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAccessLevel(request: r, options: o)
        })
    }

    public func updateAccessLevel(
      request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAccessLevelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAccessLevel(request: r, options: o)
        })
    }

    public func deleteAccessLevel(
      request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAccessLevelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAccessLevel(request: r, options: o)
        })
    }

    public func replaceAccessLevels(
      request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ReplaceAccessLevelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.replaceAccessLevels(request: r, options: o)
        })
    }

    public func listServicePerimeters(
      request: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServicePerimetersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse
          in
          return try await self.inner.listServicePerimeters(request: r, options: o)
        })
    }

    public func getServicePerimeter(
      request: GetServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServicePerimeterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.ServicePerimeter
          in
          return try await self.inner.getServicePerimeter(request: r, options: o)
        })
    }

    public func createServicePerimeter(
      request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServicePerimeterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServicePerimeter(request: r, options: o)
        })
    }

    public func updateServicePerimeter(
      request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServicePerimeterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServicePerimeter(request: r, options: o)
        })
    }

    public func deleteServicePerimeter(
      request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServicePerimeterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServicePerimeter(request: r, options: o)
        })
    }

    public func replaceServicePerimeters(
      request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ReplaceServicePerimetersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.replaceServicePerimeters(request: r, options: o)
        })
    }

    public func commitServicePerimeters(
      request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CommitServicePerimetersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.commitServicePerimeters(request: r, options: o)
        })
    }

    public func listGcpUserAccessBindings(
      request: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGcpUserAccessBindingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse
          in
          return try await self.inner.listGcpUserAccessBindings(request: r, options: o)
        })
    }

    public func getGcpUserAccessBinding(
      request: GetGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGcpUserAccessBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding
          in
          return try await self.inner.getGcpUserAccessBinding(request: r, options: o)
        })
    }

    public func createGcpUserAccessBinding(
      request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGcpUserAccessBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGcpUserAccessBinding(request: r, options: o)
        })
    }

    public func updateGcpUserAccessBinding(
      request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGcpUserAccessBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGcpUserAccessBinding(request: r, options: o)
        })
    }

    public func deleteGcpUserAccessBinding(
      request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGcpUserAccessBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGcpUserAccessBinding(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
