// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol AccessContextManagerStub: Sendable {
    func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse

    func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy

    func createAccessPolicy(
      request: AccessPolicy, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAccessLevels(
      request: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse

    func getAccessLevel(
      request: GetAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel

    func createAccessLevel(
      request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateAccessLevel(
      request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAccessLevel(
      request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func replaceAccessLevels(
      request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listServicePerimeters(
      request: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse

    func getServicePerimeter(
      request: GetServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter

    func createServicePerimeter(
      request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateServicePerimeter(
      request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteServicePerimeter(
      request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func replaceServicePerimeters(
      request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func commitServicePerimeters(
      request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGcpUserAccessBindings(
      request: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse

    func getGcpUserAccessBinding(
      request: GetGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding

    func createGcpUserAccessBinding(
      request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateGcpUserAccessBinding(
      request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteGcpUserAccessBinding(
      request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
