// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// API for setting [access levels]
/// [google.identity.accesscontextmanager.v1.AccessLevel] and [service
/// perimeters] [google.identity.accesscontextmanager.v1.ServicePerimeter]
/// for Google Cloud projects. Each organization has one [access policy]
/// [google.identity.accesscontextmanager.v1.AccessPolicy] that contains the
/// [access levels] [google.identity.accesscontextmanager.v1.AccessLevel]
/// and [service perimeters]
/// [google.identity.accesscontextmanager.v1.ServicePerimeter]. This
/// [access policy] [google.identity.accesscontextmanager.v1.AccessPolicy] is
/// applicable to all resources in the organization.
/// AccessPolicies
///
/// @Snippet(path: "AccessContextManagerQuickstart")
public final class AccessContextManagerClient: Clients.AccessContextManagerProtocol, Sendable {
  let inner: any Clients.AccessContextManagerStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AccessContextManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AccessContextManagerStub = try Clients.AccessContextManagerTransport(
      options)
    inner = Clients.AccessContextManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AccessContextManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all [access policies]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] in an
  /// organization.
  ///
  /// @Snippet(path: "AccessContextManager_ListAccessPolicies")
  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse {
    try await self.inner.listAccessPolicies(request: request, options: options)
  }

  /// Returns an [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] based on the name.
  ///
  /// @Snippet(path: "AccessContextManager_GetAccessPolicy")
  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy {
    try await self.inner.getAccessPolicy(request: request, options: options)
  }

  /// Creates an access policy. This method fails if the organization already has
  /// an access policy. The long-running operation has a successful status
  /// after the access policy propagates to long-lasting storage.
  /// Syntactic and basic semantic errors are returned in `metadata` as a
  /// BadRequest proto.
  ///
  /// @Snippet(path: "AccessContextManager_CreateAccessPolicy")
  public func createAccessPolicy(
    request: AccessPolicy, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAccessPolicy(request: request, options: options)
  }

  /// Creates an access policy. This method fails if the organization already has
  /// an access policy. The long-running operation has a successful status
  /// after the access policy propagates to long-lasting storage.
  /// Syntactic and basic semantic errors are returned in `metadata` as a
  /// BadRequest proto.
  ///
  /// @Snippet(path: "AccessContextManager_CreateAccessPolicy")
  public func createAccessPolicyPollingUntilDone(
    request: AccessPolicy, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.createAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]. The
  /// long-running operation from this RPC has a successful status after the
  /// changes to the [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] propagate
  /// to long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateAccessPolicy")
  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAccessPolicy(request: request, options: options)
  }

  /// Updates an [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]. The
  /// long-running operation from this RPC has a successful status after the
  /// changes to the [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] propagate
  /// to long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateAccessPolicy")
  public func updateAccessPolicyPollingUntilDone(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.updateAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] based on the
  /// resource name. The long-running operation has a successful status after the
  /// [access policy] [google.identity.accesscontextmanager.v1.AccessPolicy]
  /// is removed from long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteAccessPolicy")
  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAccessPolicy(request: request, options: options)
  }

  /// Deletes an [access policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] based on the
  /// resource name. The long-running operation has a successful status after the
  /// [access policy] [google.identity.accesscontextmanager.v1.AccessPolicy]
  /// is removed from long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteAccessPolicy")
  public func deleteAccessPolicyPollingUntilDone(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] for an access
  /// policy.
  ///
  /// @Snippet(path: "AccessContextManager_ListAccessLevels")
  public func listAccessLevels(
    request: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse {
    try await self.inner.listAccessLevels(request: request, options: options)
  }

  /// Gets an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] based on the resource
  /// name.
  ///
  /// @Snippet(path: "AccessContextManager_GetAccessLevel")
  public func getAccessLevel(
    request: GetAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel {
    try await self.inner.getAccessLevel(request: request, options: options)
  }

  /// Creates an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel]. The long-running
  /// operation from this RPC has a successful status after the [access
  /// level] [google.identity.accesscontextmanager.v1.AccessLevel]
  /// propagates to long-lasting storage. If [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contain
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_CreateAccessLevel")
  public func createAccessLevel(
    request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAccessLevel(request: request, options: options)
  }

  /// Creates an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel]. The long-running
  /// operation from this RPC has a successful status after the [access
  /// level] [google.identity.accesscontextmanager.v1.AccessLevel]
  /// propagates to long-lasting storage. If [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contain
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_CreateAccessLevel")
  public func createAccessLevelPollingUntilDone(
    request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      return try op._extractStatus(AccessLevel.self)
    }
    let rawOp = try await self.createAccessLevel(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel]. The long-running
  /// operation from this RPC has a successful status after the changes to
  /// the [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] propagate
  /// to long-lasting storage. If [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contain
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateAccessLevel")
  public func updateAccessLevel(
    request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAccessLevel(request: request, options: options)
  }

  /// Updates an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel]. The long-running
  /// operation from this RPC has a successful status after the changes to
  /// the [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] propagate
  /// to long-lasting storage. If [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contain
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateAccessLevel")
  public func updateAccessLevelPollingUntilDone(
    request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      return try op._extractStatus(AccessLevel.self)
    }
    let rawOp = try await self.updateAccessLevel(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] based on the resource
  /// name. The long-running operation from this RPC has a successful status
  /// after the [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] has been removed
  /// from long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteAccessLevel")
  public func deleteAccessLevel(
    request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAccessLevel(request: request, options: options)
  }

  /// Deletes an [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] based on the resource
  /// name. The long-running operation from this RPC has a successful status
  /// after the [access level]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] has been removed
  /// from long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteAccessLevel")
  public func deleteAccessLevelPollingUntilDone(
    request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAccessLevel(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Replaces all existing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] in an [access
  /// policy] [google.identity.accesscontextmanager.v1.AccessPolicy] with
  /// the [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] provided. This
  /// is done atomically. The long-running operation from this RPC has a
  /// successful status after all replacements propagate to long-lasting
  /// storage. If the replacement contains errors, an error response is returned
  /// for the first error encountered.  Upon error, the replacement is cancelled,
  /// and existing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] are not
  /// affected. The Operation.response field contains
  /// ReplaceAccessLevelsResponse. Removing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contained in existing
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] result in an
  /// error.
  ///
  /// @Snippet(path: "AccessContextManager_ReplaceAccessLevels")
  public func replaceAccessLevels(
    request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.replaceAccessLevels(request: request, options: options)
  }

  /// Replaces all existing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] in an [access
  /// policy] [google.identity.accesscontextmanager.v1.AccessPolicy] with
  /// the [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] provided. This
  /// is done atomically. The long-running operation from this RPC has a
  /// successful status after all replacements propagate to long-lasting
  /// storage. If the replacement contains errors, an error response is returned
  /// for the first error encountered.  Upon error, the replacement is cancelled,
  /// and existing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] are not
  /// affected. The Operation.response field contains
  /// ReplaceAccessLevelsResponse. Removing [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] contained in existing
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] result in an
  /// error.
  ///
  /// @Snippet(path: "AccessContextManager_ReplaceAccessLevels")
  public func replaceAccessLevelsPollingUntilDone(
    request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ReplaceAccessLevelsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ReplaceAccessLevelsResponse>.State in
      return try op._extractStatus(ReplaceAccessLevelsResponse.self)
    }
    let rawOp = try await self.replaceAccessLevels(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ReplaceAccessLevelsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] for an
  /// access policy.
  ///
  /// @Snippet(path: "AccessContextManager_ListServicePerimeters")
  public func listServicePerimeters(
    request: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse {
    try await self.inner.listServicePerimeters(request: request, options: options)
  }

  /// Gets a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] based on the
  /// resource name.
  ///
  /// @Snippet(path: "AccessContextManager_GetServicePerimeter")
  public func getServicePerimeter(
    request: GetServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter {
    try await self.inner.getServicePerimeter(request: request, options: options)
  }

  /// Creates a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]. The
  /// long-running operation from this RPC has a successful status after the
  /// [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]
  /// propagates to long-lasting storage. If a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] contains
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_CreateServicePerimeter")
  public func createServicePerimeter(
    request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServicePerimeter(request: request, options: options)
  }

  /// Creates a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]. The
  /// long-running operation from this RPC has a successful status after the
  /// [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]
  /// propagates to long-lasting storage. If a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] contains
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_CreateServicePerimeter")
  public func createServicePerimeterPollingUntilDone(
    request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      return try op._extractStatus(ServicePerimeter.self)
    }
    let rawOp = try await self.createServicePerimeter(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]. The
  /// long-running operation from this RPC has a successful status after the
  /// [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]
  /// propagates to long-lasting storage. If a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] contains
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateServicePerimeter")
  public func updateServicePerimeter(
    request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateServicePerimeter(request: request, options: options)
  }

  /// Updates a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]. The
  /// long-running operation from this RPC has a successful status after the
  /// [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter]
  /// propagates to long-lasting storage. If a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] contains
  /// errors, an error response is returned for the first error encountered.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateServicePerimeter")
  public func updateServicePerimeterPollingUntilDone(
    request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      return try op._extractStatus(ServicePerimeter.self)
    }
    let rawOp = try await self.updateServicePerimeter(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] based on the
  /// resource name. The long-running operation from this RPC has a successful
  /// status after the [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] is removed from
  /// long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteServicePerimeter")
  public func deleteServicePerimeter(
    request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServicePerimeter(request: request, options: options)
  }

  /// Deletes a [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] based on the
  /// resource name. The long-running operation from this RPC has a successful
  /// status after the [service perimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] is removed from
  /// long-lasting storage.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteServicePerimeter")
  public func deleteServicePerimeterPollingUntilDone(
    request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServicePerimeter(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Replace all existing [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] in an [access
  /// policy] [google.identity.accesscontextmanager.v1.AccessPolicy] with the
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] provided. This
  /// is done atomically. The long-running operation from this RPC has a
  /// successful status after all replacements propagate to long-lasting storage.
  /// Replacements containing errors result in an error response for the first
  /// error encountered. Upon an error, replacement are cancelled and existing
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] are not
  /// affected. The Operation.response field contains
  /// ReplaceServicePerimetersResponse.
  ///
  /// @Snippet(path: "AccessContextManager_ReplaceServicePerimeters")
  public func replaceServicePerimeters(
    request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.replaceServicePerimeters(request: request, options: options)
  }

  /// Replace all existing [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] in an [access
  /// policy] [google.identity.accesscontextmanager.v1.AccessPolicy] with the
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] provided. This
  /// is done atomically. The long-running operation from this RPC has a
  /// successful status after all replacements propagate to long-lasting storage.
  /// Replacements containing errors result in an error response for the first
  /// error encountered. Upon an error, replacement are cancelled and existing
  /// [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] are not
  /// affected. The Operation.response field contains
  /// ReplaceServicePerimetersResponse.
  ///
  /// @Snippet(path: "AccessContextManager_ReplaceServicePerimeters")
  public func replaceServicePerimetersPollingUntilDone(
    request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ReplaceServicePerimetersResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ReplaceServicePerimetersResponse>.State in
      return try op._extractStatus(ReplaceServicePerimetersResponse.self)
    }
    let rawOp = try await self.replaceServicePerimeters(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ReplaceServicePerimetersResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Commits the dry-run specification for all the [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] in an
  /// [access policy][google.identity.accesscontextmanager.v1.AccessPolicy].
  /// A commit operation on a service perimeter involves copying its `spec` field
  /// to the `status` field of the service perimeter. Only [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] with
  /// `use_explicit_dry_run_spec` field set to true are affected by a commit
  /// operation. The long-running operation from this RPC has a successful
  /// status after the dry-run specifications for all the [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] have been
  /// committed. If a commit fails, it causes the long-running operation to
  /// return an error response and the entire commit operation is cancelled.
  /// When successful, the Operation.response field contains
  /// CommitServicePerimetersResponse. The `dry_run` and the `spec` fields are
  /// cleared after a successful commit operation.
  ///
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]: <doc:AccessPolicy>
  ///
  /// @Snippet(path: "AccessContextManager_CommitServicePerimeters")
  public func commitServicePerimeters(
    request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.commitServicePerimeters(request: request, options: options)
  }

  /// Commits the dry-run specification for all the [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] in an
  /// [access policy][google.identity.accesscontextmanager.v1.AccessPolicy].
  /// A commit operation on a service perimeter involves copying its `spec` field
  /// to the `status` field of the service perimeter. Only [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] with
  /// `use_explicit_dry_run_spec` field set to true are affected by a commit
  /// operation. The long-running operation from this RPC has a successful
  /// status after the dry-run specifications for all the [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] have been
  /// committed. If a commit fails, it causes the long-running operation to
  /// return an error response and the entire commit operation is cancelled.
  /// When successful, the Operation.response field contains
  /// CommitServicePerimetersResponse. The `dry_run` and the `spec` fields are
  /// cleared after a successful commit operation.
  ///
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]: <doc:AccessPolicy>
  ///
  /// @Snippet(path: "AccessContextManager_CommitServicePerimeters")
  public func commitServicePerimetersPollingUntilDone(
    request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CommitServicePerimetersResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CommitServicePerimetersResponse>.State in
      return try op._extractStatus(CommitServicePerimetersResponse.self)
    }
    let rawOp = try await self.commitServicePerimeters(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<CommitServicePerimetersResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all [GcpUserAccessBindings]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding] for a
  /// Google Cloud organization.
  ///
  /// @Snippet(path: "AccessContextManager_ListGcpUserAccessBindings")
  public func listGcpUserAccessBindings(
    request: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse {
    try await self.inner.listGcpUserAccessBindings(request: request, options: options)
  }

  /// Gets the [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding] with
  /// the given name.
  ///
  /// @Snippet(path: "AccessContextManager_GetGcpUserAccessBinding")
  public func getGcpUserAccessBinding(
    request: GetGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding {
    try await self.inner.getGcpUserAccessBinding(request: request, options: options)
  }

  /// Creates a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding]. If the
  /// client specifies a [name]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding.name],
  /// the server ignores it. Fails if a resource already exists with the same
  /// [group_key]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding.group_key].
  /// Completion of this long-running operation does not necessarily signify that
  /// the new binding is deployed onto all affected users, which may take more
  /// time.
  ///
  /// @Snippet(path: "AccessContextManager_CreateGcpUserAccessBinding")
  public func createGcpUserAccessBinding(
    request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createGcpUserAccessBinding(request: request, options: options)
  }

  /// Creates a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding]. If the
  /// client specifies a [name]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding.name],
  /// the server ignores it. Fails if a resource already exists with the same
  /// [group_key]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding.group_key].
  /// Completion of this long-running operation does not necessarily signify that
  /// the new binding is deployed onto all affected users, which may take more
  /// time.
  ///
  /// @Snippet(path: "AccessContextManager_CreateGcpUserAccessBinding")
  public func createGcpUserAccessBindingPollingUntilDone(
    request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      return try op._extractStatus(GcpUserAccessBinding.self)
    }
    let rawOp = try await self.createGcpUserAccessBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding].
  /// Completion of this long-running operation does not necessarily signify that
  /// the changed binding is deployed onto all affected users, which may take
  /// more time.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateGcpUserAccessBinding")
  public func updateGcpUserAccessBinding(
    request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateGcpUserAccessBinding(request: request, options: options)
  }

  /// Updates a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding].
  /// Completion of this long-running operation does not necessarily signify that
  /// the changed binding is deployed onto all affected users, which may take
  /// more time.
  ///
  /// @Snippet(path: "AccessContextManager_UpdateGcpUserAccessBinding")
  public func updateGcpUserAccessBindingPollingUntilDone(
    request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      return try op._extractStatus(GcpUserAccessBinding.self)
    }
    let rawOp = try await self.updateGcpUserAccessBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding].
  /// Completion of this long-running operation does not necessarily signify that
  /// the binding deletion is deployed onto all affected users, which may take
  /// more time.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteGcpUserAccessBinding")
  public func deleteGcpUserAccessBinding(
    request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteGcpUserAccessBinding(request: request, options: options)
  }

  /// Deletes a [GcpUserAccessBinding]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding].
  /// Completion of this long-running operation does not necessarily signify that
  /// the binding deletion is deployed onto all affected users, which may take
  /// more time.
  ///
  /// @Snippet(path: "AccessContextManager_DeleteGcpUserAccessBinding")
  public func deleteGcpUserAccessBindingPollingUntilDone(
    request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteGcpUserAccessBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Sets the IAM policy for the specified Access Context Manager
  /// [access policy][google.identity.accesscontextmanager.v1.AccessPolicy].
  /// This method replaces the existing IAM policy on the access policy. The IAM
  /// policy controls the set of users who can perform specific operations on the
  /// Access Context Manager [access
  /// policy][google.identity.accesscontextmanager.v1.AccessPolicy].
  ///
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]: <doc:AccessPolicy>
  ///
  /// @Snippet(path: "AccessContextManager_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the IAM policy for the specified Access Context Manager
  /// [access policy][google.identity.accesscontextmanager.v1.AccessPolicy].
  ///
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]: <doc:AccessPolicy>
  ///
  /// @Snippet(path: "AccessContextManager_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns the IAM permissions that the caller has on the specified Access
  /// Context Manager resource. The resource can be an
  /// [AccessPolicy][google.identity.accesscontextmanager.v1.AccessPolicy],
  /// [AccessLevel][google.identity.accesscontextmanager.v1.AccessLevel], or
  /// [ServicePerimeter][google.identity.accesscontextmanager.v1.ServicePerimeter
  /// ]. This method does not support other resources.
  ///
  /// [google.identity.accesscontextmanager.v1.AccessLevel]: <doc:AccessLevel>
  /// [google.identity.accesscontextmanager.v1.AccessPolicy]: <doc:AccessPolicy>
  ///
  /// @Snippet(path: "AccessContextManager_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AccessContextManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AccessContextManagerClient`.
  ///
  /// To mock `AccessContextManagerClient` change your functions to receive
  /// `some AccessContextManagerProtocol` or `any AccessContextManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AccessContextManagerProtocol: Sendable {
    /// See `AccessContextManagerClient.createAccessPolicy`.
    func createAccessPolicyPollingUntilDone(request: AccessPolicy) async throws -> any GoogleGax
      .PollableOperation<AccessPolicy>

    /// See `AccessContextManagerClient.updateAccessPolicy`.
    func updateAccessPolicyPollingUntilDone(request: UpdateAccessPolicyRequest) async throws
      -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessContextManagerClient.updateAccessPolicy`.
    func updateAccessPolicyPollingUntilDone(
      policy: AccessPolicy?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessContextManagerClient.deleteAccessPolicy`.
    func deleteAccessPolicyPollingUntilDone(request: DeleteAccessPolicyRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.deleteAccessPolicy`.
    func deleteAccessPolicyPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.createAccessLevel`.
    func createAccessLevelPollingUntilDone(request: CreateAccessLevelRequest) async throws
      -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.createAccessLevel`.
    func createAccessLevelPollingUntilDone(
      parent: Swift.String,
      accessLevel: AccessLevel?,
    ) async throws -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.updateAccessLevel`.
    func updateAccessLevelPollingUntilDone(request: UpdateAccessLevelRequest) async throws
      -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.updateAccessLevel`.
    func updateAccessLevelPollingUntilDone(
      accessLevel: AccessLevel?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.deleteAccessLevel`.
    func deleteAccessLevelPollingUntilDone(request: DeleteAccessLevelRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.deleteAccessLevel`.
    func deleteAccessLevelPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.replaceAccessLevels`.
    func replaceAccessLevelsPollingUntilDone(request: ReplaceAccessLevelsRequest) async throws
      -> any GoogleGax.PollableOperation<ReplaceAccessLevelsResponse>

    /// See `AccessContextManagerClient.createServicePerimeter`.
    func createServicePerimeterPollingUntilDone(request: CreateServicePerimeterRequest) async throws
      -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.createServicePerimeter`.
    func createServicePerimeterPollingUntilDone(
      parent: Swift.String,
      servicePerimeter: ServicePerimeter?,
    ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.updateServicePerimeter`.
    func updateServicePerimeterPollingUntilDone(request: UpdateServicePerimeterRequest) async throws
      -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.updateServicePerimeter`.
    func updateServicePerimeterPollingUntilDone(
      servicePerimeter: ServicePerimeter?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.deleteServicePerimeter`.
    func deleteServicePerimeterPollingUntilDone(request: DeleteServicePerimeterRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.deleteServicePerimeter`.
    func deleteServicePerimeterPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.replaceServicePerimeters`.
    func replaceServicePerimetersPollingUntilDone(request: ReplaceServicePerimetersRequest)
      async throws -> any GoogleGax.PollableOperation<ReplaceServicePerimetersResponse>

    /// See `AccessContextManagerClient.commitServicePerimeters`.
    func commitServicePerimetersPollingUntilDone(request: CommitServicePerimetersRequest)
      async throws -> any GoogleGax.PollableOperation<CommitServicePerimetersResponse>

    /// See `AccessContextManagerClient.createGcpUserAccessBinding`.
    func createGcpUserAccessBindingPollingUntilDone(request: CreateGcpUserAccessBindingRequest)
      async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.createGcpUserAccessBinding`.
    func createGcpUserAccessBindingPollingUntilDone(
      parent: Swift.String,
      gcpUserAccessBinding: GcpUserAccessBinding?,
    ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.updateGcpUserAccessBinding`.
    func updateGcpUserAccessBindingPollingUntilDone(request: UpdateGcpUserAccessBindingRequest)
      async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.updateGcpUserAccessBinding`.
    func updateGcpUserAccessBindingPollingUntilDone(
      gcpUserAccessBinding: GcpUserAccessBinding?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.deleteGcpUserAccessBinding`.
    func deleteGcpUserAccessBindingPollingUntilDone(request: DeleteGcpUserAccessBindingRequest)
      async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.deleteGcpUserAccessBinding`.
    func deleteGcpUserAccessBindingPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.listAccessPolicies`.
    func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse

    /// See `AccessContextManagerClient.getAccessPolicy`.
    func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy

    /// See `AccessContextManagerClient.createAccessPolicy`.
    func createAccessPolicy(
      request: AccessPolicy, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.createAccessPolicy`.
    func createAccessPolicyPollingUntilDone(
      request: AccessPolicy, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessContextManagerClient.updateAccessPolicy`.
    func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.updateAccessPolicy`.
    func updateAccessPolicyPollingUntilDone(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessContextManagerClient.deleteAccessPolicy`.
    func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.deleteAccessPolicy`.
    func deleteAccessPolicyPollingUntilDone(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.listAccessLevels`.
    func listAccessLevels(
      request: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse

    /// See `AccessContextManagerClient.getAccessLevel`.
    func getAccessLevel(
      request: GetAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel

    /// See `AccessContextManagerClient.createAccessLevel`.
    func createAccessLevel(
      request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.createAccessLevel`.
    func createAccessLevelPollingUntilDone(
      request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.updateAccessLevel`.
    func updateAccessLevel(
      request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.updateAccessLevel`.
    func updateAccessLevelPollingUntilDone(
      request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessLevel>

    /// See `AccessContextManagerClient.deleteAccessLevel`.
    func deleteAccessLevel(
      request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.deleteAccessLevel`.
    func deleteAccessLevelPollingUntilDone(
      request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.replaceAccessLevels`.
    func replaceAccessLevels(
      request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.replaceAccessLevels`.
    func replaceAccessLevelsPollingUntilDone(
      request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ReplaceAccessLevelsResponse>

    /// See `AccessContextManagerClient.listServicePerimeters`.
    func listServicePerimeters(
      request: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse

    /// See `AccessContextManagerClient.getServicePerimeter`.
    func getServicePerimeter(
      request: GetServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter

    /// See `AccessContextManagerClient.createServicePerimeter`.
    func createServicePerimeter(
      request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.createServicePerimeter`.
    func createServicePerimeterPollingUntilDone(
      request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.updateServicePerimeter`.
    func updateServicePerimeter(
      request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.updateServicePerimeter`.
    func updateServicePerimeterPollingUntilDone(
      request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter>

    /// See `AccessContextManagerClient.deleteServicePerimeter`.
    func deleteServicePerimeter(
      request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.deleteServicePerimeter`.
    func deleteServicePerimeterPollingUntilDone(
      request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.replaceServicePerimeters`.
    func replaceServicePerimeters(
      request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.replaceServicePerimeters`.
    func replaceServicePerimetersPollingUntilDone(
      request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ReplaceServicePerimetersResponse>

    /// See `AccessContextManagerClient.commitServicePerimeters`.
    func commitServicePerimeters(
      request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.commitServicePerimeters`.
    func commitServicePerimetersPollingUntilDone(
      request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<CommitServicePerimetersResponse>

    /// See `AccessContextManagerClient.listGcpUserAccessBindings`.
    func listGcpUserAccessBindings(
      request: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse

    /// See `AccessContextManagerClient.getGcpUserAccessBinding`.
    func getGcpUserAccessBinding(
      request: GetGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding

    /// See `AccessContextManagerClient.createGcpUserAccessBinding`.
    func createGcpUserAccessBinding(
      request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.createGcpUserAccessBinding`.
    func createGcpUserAccessBindingPollingUntilDone(
      request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.updateGcpUserAccessBinding`.
    func updateGcpUserAccessBinding(
      request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.updateGcpUserAccessBinding`.
    func updateGcpUserAccessBindingPollingUntilDone(
      request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>

    /// See `AccessContextManagerClient.deleteGcpUserAccessBinding`.
    func deleteGcpUserAccessBinding(
      request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessContextManagerClient.deleteGcpUserAccessBinding`.
    func deleteGcpUserAccessBindingPollingUntilDone(
      request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessContextManagerClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AccessContextManagerClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AccessContextManagerClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse
  }
}

// Default implementations
extension Clients.AccessContextManagerProtocol {
  public func listAccessPolicies(request: ListAccessPoliciesRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse
  {
    try await self.listAccessPolicies(request: request, options: .init())
  }

  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAccessPolicies(
    byItem: ListAccessPoliciesRequest
  ) -> any AsyncSequence<AccessPolicy, Swift.Error> {
    self.listAccessPolicies(byItem: byItem, options: .init())
  }

  /// Lists all [access policies]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] in an
  /// organization.
  ///
  /// @Snippet(path: "AccessContextManager_ListAccessPolicies")
  public func listAccessPolicies(
    byItem: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AccessPolicy, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleIdentityAccessContextManagerV1.ListAccessPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAccessPolicies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getAccessPolicy(request: GetAccessPolicyRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.AccessPolicy
  {
    try await self.getAccessPolicy(request: request, options: .init())
  }

  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAccessPolicy(
    name: Swift.String,
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessPolicy {
    let request = GetAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.getAccessPolicy(request: request)
  }

  public func createAccessPolicy(request: AccessPolicy) async throws -> GoogleLongRunning.Operation
  {
    try await self.createAccessPolicy(request: request, options: .init())
  }

  public func createAccessPolicy(
    request: AccessPolicy, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAccessPolicyPollingUntilDone(request: AccessPolicy) async throws
    -> any GoogleGax.PollableOperation<AccessPolicy>
  {
    try await self.createAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func createAccessPolicyPollingUntilDone(
    request: AccessPolicy, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAccessPolicy(request: UpdateAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAccessPolicy(request: request, options: .init())
  }

  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAccessPolicyPollingUntilDone(request: UpdateAccessPolicyRequest) async throws
    -> any GoogleGax.PollableOperation<AccessPolicy>
  {
    try await self.updateAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func updateAccessPolicyPollingUntilDone(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAccessPolicyPollingUntilDone(
    policy: AccessPolicy?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let request = UpdateAccessPolicyRequest().with {
      $0.policy = policy
      $0.updateMask = updateMask
    }
    return try await self.updateAccessPolicyPollingUntilDone(request: request)
  }

  public func deleteAccessPolicy(request: DeleteAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAccessPolicy(request: request, options: .init())
  }

  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAccessPolicyPollingUntilDone(request: DeleteAccessPolicyRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func deleteAccessPolicyPollingUntilDone(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessPolicyPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.deleteAccessPolicyPollingUntilDone(request: request)
  }

  public func listAccessLevels(request: ListAccessLevelsRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse
  {
    try await self.listAccessLevels(request: request, options: .init())
  }

  public func listAccessLevels(
    request: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAccessLevels(
    byItem: ListAccessLevelsRequest
  ) -> any AsyncSequence<AccessLevel, Swift.Error> {
    self.listAccessLevels(byItem: byItem, options: .init())
  }

  /// Lists all [access levels]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] for an access
  /// policy.
  ///
  /// @Snippet(path: "AccessContextManager_ListAccessLevels")
  public func listAccessLevels(
    byItem: ListAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AccessLevel, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleIdentityAccessContextManagerV1.ListAccessLevelsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAccessLevels(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAccessLevels(
    parent: Swift.String,
  ) -> any AsyncSequence<AccessLevel, Swift.Error> {
    let request = ListAccessLevelsRequest().with {
      $0.parent = parent
    }
    return self.listAccessLevels(byItem: request)
  }

  public func getAccessLevel(request: GetAccessLevelRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.AccessLevel
  {
    try await self.getAccessLevel(request: request, options: .init())
  }

  public func getAccessLevel(
    request: GetAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAccessLevel(
    name: Swift.String,
  ) async throws -> GoogleIdentityAccessContextManagerV1.AccessLevel {
    let request = GetAccessLevelRequest().with {
      $0.name = name
    }
    return try await self.getAccessLevel(request: request)
  }

  public func createAccessLevel(request: CreateAccessLevelRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAccessLevel(request: request, options: .init())
  }

  public func createAccessLevel(
    request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAccessLevelPollingUntilDone(request: CreateAccessLevelRequest) async throws
    -> any GoogleGax.PollableOperation<AccessLevel>
  {
    try await self.createAccessLevelPollingUntilDone(request: request, options: .init())
  }

  public func createAccessLevelPollingUntilDone(
    request: CreateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAccessLevelPollingUntilDone(
    parent: Swift.String,
    accessLevel: AccessLevel?,
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let request = CreateAccessLevelRequest().with {
      $0.parent = parent
      $0.accessLevel = accessLevel
    }
    return try await self.createAccessLevelPollingUntilDone(request: request)
  }

  public func updateAccessLevel(request: UpdateAccessLevelRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAccessLevel(request: request, options: .init())
  }

  public func updateAccessLevel(
    request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAccessLevelPollingUntilDone(request: UpdateAccessLevelRequest) async throws
    -> any GoogleGax.PollableOperation<AccessLevel>
  {
    try await self.updateAccessLevelPollingUntilDone(request: request, options: .init())
  }

  public func updateAccessLevelPollingUntilDone(
    request: UpdateAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccessLevel>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAccessLevelPollingUntilDone(
    accessLevel: AccessLevel?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AccessLevel> {
    let request = UpdateAccessLevelRequest().with {
      $0.accessLevel = accessLevel
      $0.updateMask = updateMask
    }
    return try await self.updateAccessLevelPollingUntilDone(request: request)
  }

  public func deleteAccessLevel(request: DeleteAccessLevelRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAccessLevel(request: request, options: .init())
  }

  public func deleteAccessLevel(
    request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAccessLevelPollingUntilDone(request: DeleteAccessLevelRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAccessLevelPollingUntilDone(request: request, options: .init())
  }

  public func deleteAccessLevelPollingUntilDone(
    request: DeleteAccessLevelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessLevelPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAccessLevelRequest().with {
      $0.name = name
    }
    return try await self.deleteAccessLevelPollingUntilDone(request: request)
  }

  public func replaceAccessLevels(request: ReplaceAccessLevelsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.replaceAccessLevels(request: request, options: .init())
  }

  public func replaceAccessLevels(
    request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func replaceAccessLevelsPollingUntilDone(request: ReplaceAccessLevelsRequest) async throws
    -> any GoogleGax.PollableOperation<ReplaceAccessLevelsResponse>
  {
    try await self.replaceAccessLevelsPollingUntilDone(request: request, options: .init())
  }

  public func replaceAccessLevelsPollingUntilDone(
    request: ReplaceAccessLevelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ReplaceAccessLevelsResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ReplaceAccessLevelsResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listServicePerimeters(request: ListServicePerimetersRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse
  {
    try await self.listServicePerimeters(request: request, options: .init())
  }

  public func listServicePerimeters(
    request: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServicePerimeters(
    byItem: ListServicePerimetersRequest
  ) -> any AsyncSequence<ServicePerimeter, Swift.Error> {
    self.listServicePerimeters(byItem: byItem, options: .init())
  }

  /// Lists all [service perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] for an
  /// access policy.
  ///
  /// @Snippet(path: "AccessContextManager_ListServicePerimeters")
  public func listServicePerimeters(
    byItem: ListServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ServicePerimeter, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleIdentityAccessContextManagerV1.ListServicePerimetersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServicePerimeters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listServicePerimeters(
    parent: Swift.String,
  ) -> any AsyncSequence<ServicePerimeter, Swift.Error> {
    let request = ListServicePerimetersRequest().with {
      $0.parent = parent
    }
    return self.listServicePerimeters(byItem: request)
  }

  public func getServicePerimeter(request: GetServicePerimeterRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.ServicePerimeter
  {
    try await self.getServicePerimeter(request: request, options: .init())
  }

  public func getServicePerimeter(
    request: GetServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServicePerimeter(
    name: Swift.String,
  ) async throws -> GoogleIdentityAccessContextManagerV1.ServicePerimeter {
    let request = GetServicePerimeterRequest().with {
      $0.name = name
    }
    return try await self.getServicePerimeter(request: request)
  }

  public func createServicePerimeter(request: CreateServicePerimeterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createServicePerimeter(request: request, options: .init())
  }

  public func createServicePerimeter(
    request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServicePerimeterPollingUntilDone(request: CreateServicePerimeterRequest)
    async throws -> any GoogleGax.PollableOperation<ServicePerimeter>
  {
    try await self.createServicePerimeterPollingUntilDone(request: request, options: .init())
  }

  public func createServicePerimeterPollingUntilDone(
    request: CreateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createServicePerimeterPollingUntilDone(
    parent: Swift.String,
    servicePerimeter: ServicePerimeter?,
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let request = CreateServicePerimeterRequest().with {
      $0.parent = parent
      $0.servicePerimeter = servicePerimeter
    }
    return try await self.createServicePerimeterPollingUntilDone(request: request)
  }

  public func updateServicePerimeter(request: UpdateServicePerimeterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateServicePerimeter(request: request, options: .init())
  }

  public func updateServicePerimeter(
    request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServicePerimeterPollingUntilDone(request: UpdateServicePerimeterRequest)
    async throws -> any GoogleGax.PollableOperation<ServicePerimeter>
  {
    try await self.updateServicePerimeterPollingUntilDone(request: request, options: .init())
  }

  public func updateServicePerimeterPollingUntilDone(
    request: UpdateServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ServicePerimeter>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateServicePerimeterPollingUntilDone(
    servicePerimeter: ServicePerimeter?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<ServicePerimeter> {
    let request = UpdateServicePerimeterRequest().with {
      $0.servicePerimeter = servicePerimeter
      $0.updateMask = updateMask
    }
    return try await self.updateServicePerimeterPollingUntilDone(request: request)
  }

  public func deleteServicePerimeter(request: DeleteServicePerimeterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteServicePerimeter(request: request, options: .init())
  }

  public func deleteServicePerimeter(
    request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServicePerimeterPollingUntilDone(request: DeleteServicePerimeterRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteServicePerimeterPollingUntilDone(request: request, options: .init())
  }

  public func deleteServicePerimeterPollingUntilDone(
    request: DeleteServicePerimeterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteServicePerimeterPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteServicePerimeterRequest().with {
      $0.name = name
    }
    return try await self.deleteServicePerimeterPollingUntilDone(request: request)
  }

  public func replaceServicePerimeters(request: ReplaceServicePerimetersRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.replaceServicePerimeters(request: request, options: .init())
  }

  public func replaceServicePerimeters(
    request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func replaceServicePerimetersPollingUntilDone(request: ReplaceServicePerimetersRequest)
    async throws -> any GoogleGax.PollableOperation<ReplaceServicePerimetersResponse>
  {
    try await self.replaceServicePerimetersPollingUntilDone(request: request, options: .init())
  }

  public func replaceServicePerimetersPollingUntilDone(
    request: ReplaceServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ReplaceServicePerimetersResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ReplaceServicePerimetersResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func commitServicePerimeters(request: CommitServicePerimetersRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.commitServicePerimeters(request: request, options: .init())
  }

  public func commitServicePerimeters(
    request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func commitServicePerimetersPollingUntilDone(request: CommitServicePerimetersRequest)
    async throws -> any GoogleGax.PollableOperation<CommitServicePerimetersResponse>
  {
    try await self.commitServicePerimetersPollingUntilDone(request: request, options: .init())
  }

  public func commitServicePerimetersPollingUntilDone(
    request: CommitServicePerimetersRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CommitServicePerimetersResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<CommitServicePerimetersResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listGcpUserAccessBindings(request: ListGcpUserAccessBindingsRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse
  {
    try await self.listGcpUserAccessBindings(request: request, options: .init())
  }

  public func listGcpUserAccessBindings(
    request: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGcpUserAccessBindings(
    byItem: ListGcpUserAccessBindingsRequest
  ) -> any AsyncSequence<GcpUserAccessBinding, Swift.Error> {
    self.listGcpUserAccessBindings(byItem: byItem, options: .init())
  }

  /// Lists all [GcpUserAccessBindings]
  /// [google.identity.accesscontextmanager.v1.GcpUserAccessBinding] for a
  /// Google Cloud organization.
  ///
  /// @Snippet(path: "AccessContextManager_ListGcpUserAccessBindings")
  public func listGcpUserAccessBindings(
    byItem: ListGcpUserAccessBindingsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GcpUserAccessBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleIdentityAccessContextManagerV1.ListGcpUserAccessBindingsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGcpUserAccessBindings(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGcpUserAccessBindings(
    parent: Swift.String,
  ) -> any AsyncSequence<GcpUserAccessBinding, Swift.Error> {
    let request = ListGcpUserAccessBindingsRequest().with {
      $0.parent = parent
    }
    return self.listGcpUserAccessBindings(byItem: request)
  }

  public func getGcpUserAccessBinding(request: GetGcpUserAccessBindingRequest) async throws
    -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding
  {
    try await self.getGcpUserAccessBinding(request: request, options: .init())
  }

  public func getGcpUserAccessBinding(
    request: GetGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGcpUserAccessBinding(
    name: Swift.String,
  ) async throws -> GoogleIdentityAccessContextManagerV1.GcpUserAccessBinding {
    let request = GetGcpUserAccessBindingRequest().with {
      $0.name = name
    }
    return try await self.getGcpUserAccessBinding(request: request)
  }

  public func createGcpUserAccessBinding(request: CreateGcpUserAccessBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createGcpUserAccessBinding(request: request, options: .init())
  }

  public func createGcpUserAccessBinding(
    request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGcpUserAccessBindingPollingUntilDone(request: CreateGcpUserAccessBindingRequest)
    async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>
  {
    try await self.createGcpUserAccessBindingPollingUntilDone(request: request, options: .init())
  }

  public func createGcpUserAccessBindingPollingUntilDone(
    request: CreateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createGcpUserAccessBindingPollingUntilDone(
    parent: Swift.String,
    gcpUserAccessBinding: GcpUserAccessBinding?,
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let request = CreateGcpUserAccessBindingRequest().with {
      $0.parent = parent
      $0.gcpUserAccessBinding = gcpUserAccessBinding
    }
    return try await self.createGcpUserAccessBindingPollingUntilDone(request: request)
  }

  public func updateGcpUserAccessBinding(request: UpdateGcpUserAccessBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateGcpUserAccessBinding(request: request, options: .init())
  }

  public func updateGcpUserAccessBinding(
    request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGcpUserAccessBindingPollingUntilDone(request: UpdateGcpUserAccessBindingRequest)
    async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding>
  {
    try await self.updateGcpUserAccessBindingPollingUntilDone(request: request, options: .init())
  }

  public func updateGcpUserAccessBindingPollingUntilDone(
    request: UpdateGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GcpUserAccessBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateGcpUserAccessBindingPollingUntilDone(
    gcpUserAccessBinding: GcpUserAccessBinding?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<GcpUserAccessBinding> {
    let request = UpdateGcpUserAccessBindingRequest().with {
      $0.gcpUserAccessBinding = gcpUserAccessBinding
      $0.updateMask = updateMask
    }
    return try await self.updateGcpUserAccessBindingPollingUntilDone(request: request)
  }

  public func deleteGcpUserAccessBinding(request: DeleteGcpUserAccessBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteGcpUserAccessBinding(request: request, options: .init())
  }

  public func deleteGcpUserAccessBinding(
    request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGcpUserAccessBindingPollingUntilDone(request: DeleteGcpUserAccessBindingRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteGcpUserAccessBindingPollingUntilDone(request: request, options: .init())
  }

  public func deleteGcpUserAccessBindingPollingUntilDone(
    request: DeleteGcpUserAccessBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteGcpUserAccessBindingPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteGcpUserAccessBindingRequest().with {
      $0.name = name
    }
    return try await self.deleteGcpUserAccessBindingPollingUntilDone(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
