// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A condition necessary for an `AccessLevel` to be granted. The Condition is an
/// AND over its fields. So a Condition is true if: 1) the request IP is from one
/// of the listed subnetworks AND 2) the originating device complies with the
/// listed device policy AND 3) all listed access levels are granted AND 4) the
/// request was sent at a time allowed by the DateTimeRestriction.
public struct Condition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// CIDR block IP subnetwork specification. May be IPv4 or IPv6. Note that for
  /// a CIDR IP address block, the specified IP address portion must be properly
  /// truncated (i.e. all the host bits must be zero) or the input is considered
  /// malformed. For example, "192.0.2.0/24" is accepted but "192.0.2.1/24" is
  /// not. Similarly, for IPv6, "2001:db8::/32" is accepted whereas
  /// "2001:db8::1/32" is not. The originating IP of a request must be in one of
  /// the listed subnets in order for this Condition to be true. If empty, all IP
  /// addresses are allowed.
  public var ipSubnetworks: [Swift.String] = []

  /// Device specific restrictions, all restrictions must hold for the
  /// Condition to be true. If not specified, all devices are allowed.
  public var devicePolicy: DevicePolicy? = nil

  /// A list of other access levels defined in the same `Policy`, referenced by
  /// resource name. Referencing an `AccessLevel` which does not exist is an
  /// error. All access levels listed must be granted for the Condition
  /// to be true. Example:
  /// "`accessPolicies/MY_POLICY/accessLevels/LEVEL_NAME"`
  public var requiredAccessLevels: [Swift.String] = []

  /// Whether to negate the Condition. If true, the Condition becomes a NAND over
  /// its non-empty fields, each field must be false for the Condition overall to
  /// be satisfied. Defaults to false.
  public var negate: Swift.Bool = Swift.Bool()

  /// The request must be made by one of the provided user or service
  /// accounts. Groups are not supported.
  /// Syntax:
  /// `user:{emailid}`
  /// `serviceAccount:{emailid}`
  /// If not specified, a request may come from any user.
  public var members: [Swift.String] = []

  /// The request must originate from one of the provided countries/regions.
  /// Must be valid ISO 3166-1 alpha-2 codes.
  public var regions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Condition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Condition().with { $0.ipSubnetworks = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ipSubnetworks = CodingKeys(stringValue: "ipSubnetworks")
    static let devicePolicy = CodingKeys(stringValue: "devicePolicy")
    static let requiredAccessLevels = CodingKeys(stringValue: "requiredAccessLevels")
    static let negate = CodingKeys(stringValue: "negate")
    static let members = CodingKeys(stringValue: "members")
    static let regions = CodingKeys(stringValue: "regions")

    static let _knownKeys: Set<Swift.String> = [
      "ipSubnetworks",
      "devicePolicy",
      "requiredAccessLevels",
      "negate",
      "members",
      "regions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipSubnetworks) {
      self.ipSubnetworks = value
    }
    self.devicePolicy = try container.decodeIfPresent(DevicePolicy.self, forKey: .devicePolicy)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .requiredAccessLevels)
    {
      self.requiredAccessLevels = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .negate) {
      self.negate = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .members) {
      self.members = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .regions) {
      self.regions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ipSubnetworks, forKey: .ipSubnetworks)
    try container.encodeIfPresent(self.devicePolicy, forKey: .devicePolicy)
    try container.encode(self.requiredAccessLevels, forKey: .requiredAccessLevels)
    try container.encode(self.negate, forKey: .negate)
    try container.encode(self.members, forKey: .members)
    try container.encode(self.regions, forKey: .regions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.identity.accesscontextmanager.v1.Condition"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
