// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A response to `ListAccessPoliciesRequest`.
public struct ListAccessPoliciesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// List of the AccessPolicy instances.
  public var accessPolicies: [AccessPolicy] = []

  /// The pagination token to retrieve the next page of results. If the value is
  /// empty, no further results remain.
  public var nextPageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListAccessPoliciesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAccessPoliciesResponse().with { $0.accessPolicies = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accessPolicies = CodingKeys(stringValue: "accessPolicies")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

    static let _knownKeys: Set<Swift.String> = [
      "accessPolicies",
      "nextPageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([AccessPolicy].self, forKey: .accessPolicies) {
      self.accessPolicies = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accessPolicies, forKey: .accessPolicies)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.identity.accesscontextmanager.v1.ListAccessPoliciesResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListAccessPoliciesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [AccessPolicy] {
    return self.accessPolicies
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
