// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request to replace all existing Service Perimeters in an Access Policy
/// with the Service Perimeters provided. This is done atomically.
public struct ReplaceServicePerimetersRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name for the access policy which owns these
  /// [Service Perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter].
  ///
  /// Format: `accessPolicies/{policy_id}`
  public var parent: Swift.String = Swift.String()

  /// Required. The desired [Service Perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] that should
  /// replace all existing [Service Perimeters]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] in the
  /// [Access Policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy].
  public var servicePerimeters: [ServicePerimeter] = []

  /// Optional. The etag for the version of the [Access Policy]
  /// [google.identity.accesscontextmanager.v1.AccessPolicy] that this
  /// replace operation is to be performed on. If, at the time of replace, the
  /// etag for the Access Policy stored in Access Context Manager is different
  /// from the specified etag, then the replace operation will not be performed
  /// and the call will fail. This field is not required. If etag is not
  /// provided, the operation will be performed as if a valid etag is provided.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReplaceServicePerimetersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplaceServicePerimetersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let servicePerimeters = CodingKeys(stringValue: "servicePerimeters")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "servicePerimeters",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(
      [ServicePerimeter].self, forKey: .servicePerimeters)
    {
      self.servicePerimeters = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.servicePerimeters, forKey: .servicePerimeters)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.identity.accesscontextmanager.v1.ReplaceServicePerimetersRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
