// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// `ServicePerimeterConfig` specifies a set of Google Cloud resources that
/// describe specific Service Perimeter configuration.
public struct ServicePerimeterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A list of Google Cloud resources that are inside of the service perimeter.
  /// Currently only projects are allowed. Format: `projects/{project_number}`
  public var resources: [Swift.String] = []

  /// A list of `AccessLevel` resource names that allow resources within the
  /// `ServicePerimeter` to be accessed from the internet. `AccessLevels` listed
  /// must be in the same policy as this `ServicePerimeter`. Referencing a
  /// nonexistent `AccessLevel` is a syntax error. If no `AccessLevel` names are
  /// listed, resources within the perimeter can only be accessed via Google
  /// Cloud calls with request origins within the perimeter. Example:
  /// `"accessPolicies/MY_POLICY/accessLevels/MY_LEVEL"`.
  /// For Service Perimeter Bridge, must be empty.
  public var accessLevels: [Swift.String] = []

  /// Google Cloud services that are subject to the Service Perimeter
  /// restrictions. For example, if `storage.googleapis.com` is specified, access
  /// to the storage buckets inside the perimeter must meet the perimeter's
  /// access restrictions.
  public var restrictedServices: [Swift.String] = []

  /// Configuration for APIs allowed within Perimeter.
  public var vpcAccessibleServices: ServicePerimeterConfig.VpcAccessibleServices? = nil

  /// List of [IngressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// to apply to the perimeter. A perimeter may have multiple [IngressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy],
  /// each of which is evaluated separately. Access is granted if any [Ingress
  /// Policy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// grants it. Must be empty for a perimeter bridge.
  public var ingressPolicies: [ServicePerimeterConfig.IngressPolicy] = []

  /// List of [EgressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// to apply to the perimeter. A perimeter may have multiple [EgressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy],
  /// each of which is evaluated separately. Access is granted if any
  /// [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// grants it. Must be empty for a perimeter bridge.
  public var egressPolicies: [ServicePerimeterConfig.EgressPolicy] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServicePerimeterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServicePerimeterConfig().with { $0.resources = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resources = CodingKeys(stringValue: "resources")
    static let accessLevels = CodingKeys(stringValue: "accessLevels")
    static let restrictedServices = CodingKeys(stringValue: "restrictedServices")
    static let vpcAccessibleServices = CodingKeys(stringValue: "vpcAccessibleServices")
    static let ingressPolicies = CodingKeys(stringValue: "ingressPolicies")
    static let egressPolicies = CodingKeys(stringValue: "egressPolicies")

    static let _knownKeys: Set<Swift.String> = [
      "resources",
      "accessLevels",
      "restrictedServices",
      "vpcAccessibleServices",
      "ingressPolicies",
      "egressPolicies",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resources) {
      self.resources = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .accessLevels) {
      self.accessLevels = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .restrictedServices) {
      self.restrictedServices = value
    }
    self.vpcAccessibleServices = try container.decodeIfPresent(
      ServicePerimeterConfig.VpcAccessibleServices.self, forKey: .vpcAccessibleServices)
    if let value = try container.decodeIfPresent(
      [ServicePerimeterConfig.IngressPolicy].self, forKey: .ingressPolicies)
    {
      self.ingressPolicies = value
    }
    if let value = try container.decodeIfPresent(
      [ServicePerimeterConfig.EgressPolicy].self, forKey: .egressPolicies)
    {
      self.egressPolicies = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resources, forKey: .resources)
    try container.encode(self.accessLevels, forKey: .accessLevels)
    try container.encode(self.restrictedServices, forKey: .restrictedServices)
    try container.encodeIfPresent(self.vpcAccessibleServices, forKey: .vpcAccessibleServices)
    try container.encode(self.ingressPolicies, forKey: .ingressPolicies)
    try container.encode(self.egressPolicies, forKey: .egressPolicies)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies how APIs are allowed to communicate within the Service
  /// Perimeter.
  public struct VpcAccessibleServices: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Whether to restrict API calls within the Service Perimeter to the list of
    /// APIs specified in 'allowed_services'.
    public var enableRestriction: Swift.Bool = Swift.Bool()

    /// The list of APIs usable within the Service Perimeter. Must be empty
    /// unless 'enable_restriction' is True. You can specify a list of individual
    /// services, as well as include the 'RESTRICTED-SERVICES' value, which
    /// automatically includes all of the services protected by the perimeter.
    public var allowedServices: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VpcAccessibleServices`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VpcAccessibleServices().with { $0.enableRestriction = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enableRestriction = CodingKeys(stringValue: "enableRestriction")
      static let allowedServices = CodingKeys(stringValue: "allowedServices")

      static let _knownKeys: Set<Swift.String> = [
        "enableRestriction",
        "allowedServices",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRestriction) {
        self.enableRestriction = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedServices) {
        self.allowedServices = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enableRestriction, forKey: .enableRestriction)
      try container.encode(self.allowedServices, forKey: .allowedServices)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.VpcAccessibleServices"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// An allowed method or permission of a service specified in [ApiOperation]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation].
  public struct MethodSelector: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The API method name or Cloud IAM permission name to allow.
    public var kind: OneOf_Kind? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MethodSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MethodSelector().with { $0.method = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let method = CodingKeys(stringValue: "method")
      static let permission = CodingKeys(stringValue: "permission")

      static let _knownKeys: Set<Swift.String> = [
        "method",
        "permission",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let method = try container.decodeIfPresent(Swift.String.self, forKey: .method) {
        try kindCheckAndSet(.method(method))
      }
      if let permission = try container.decodeIfPresent(Swift.String.self, forKey: .permission) {
        try kindCheckAndSet(.permission(permission))
      }
      self.kind = kind
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .method(let value):
          try container.encode(value, forKey: .method)
        case .permission(let value):
          try container.encode(value, forKey: .permission)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The API method name or Cloud IAM permission name to allow.
    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// Value for `method` should be a valid method name for the corresponding
      /// `service_name` in [ApiOperation]
      /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation].
      /// If `*` used as value for `method`, then ALL methods and permissions are
      /// allowed.
      case method(Swift.String)
      /// Value for `permission` should be a valid Cloud IAM permission for the
      /// corresponding `service_name` in [ApiOperation]
      /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation].
      case permission(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.MethodSelector"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Identification for an API Operation.
  public struct ApiOperation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the API whose methods or permissions the [IngressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
    /// or [EgressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
    /// want to allow. A single [ApiOperation]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
    /// with `service_name` field set to `*` will allow all methods AND
    /// permissions for all services.
    public var serviceName: Swift.String = Swift.String()

    /// API methods or permissions to allow. Method or permission must belong to
    /// the service specified by `service_name` field. A single [MethodSelector]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.MethodSelector]
    /// entry with `*` specified for the `method` field will allow all methods
    /// AND permissions for the service specified in `service_name`.
    public var methodSelectors: [ServicePerimeterConfig.MethodSelector] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ApiOperation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ApiOperation().with { $0.serviceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serviceName = CodingKeys(stringValue: "serviceName")
      static let methodSelectors = CodingKeys(stringValue: "methodSelectors")

      static let _knownKeys: Set<Swift.String> = [
        "serviceName",
        "methodSelectors",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceName) {
        self.serviceName = value
      }
      if let value = try container.decodeIfPresent(
        [ServicePerimeterConfig.MethodSelector].self, forKey: .methodSelectors)
      {
        self.methodSelectors = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serviceName, forKey: .serviceName)
      try container.encode(self.methodSelectors, forKey: .methodSelectors)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The source that [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// authorizes access from.
  public struct IngressSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Allowed ingress source. It can be one of [AccessLevel]
    /// [google.identity.accesscontextmanager.v1.AccessLevel] or Google
    /// Cloud resource.
    public var source: OneOf_Source? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IngressSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IngressSource().with { $0.accessLevel = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let accessLevel = CodingKeys(stringValue: "accessLevel")
      static let resource = CodingKeys(stringValue: "resource")

      static let _knownKeys: Set<Swift.String> = [
        "accessLevel",
        "resource",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let accessLevel = try container.decodeIfPresent(Swift.String.self, forKey: .accessLevel) {
        try sourceCheckAndSet(.accessLevel(accessLevel))
      }
      if let resource = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
        try sourceCheckAndSet(.resource(resource))
      }
      self.source = source
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.source {
        switch choice {
        case .accessLevel(let value):
          try container.encode(value, forKey: .accessLevel)
        case .resource(let value):
          try container.encode(value, forKey: .resource)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Allowed ingress source. It can be one of [AccessLevel]
    /// [google.identity.accesscontextmanager.v1.AccessLevel] or Google
    /// Cloud resource.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// An [AccessLevel]
      /// [google.identity.accesscontextmanager.v1.AccessLevel] resource
      /// name that allow resources within the [ServicePerimeters]
      /// [google.identity.accesscontextmanager.v1.ServicePerimeter] to be
      /// accessed from the internet. [AccessLevels]
      /// [google.identity.accesscontextmanager.v1.AccessLevel] listed must
      /// be in the same policy as this [ServicePerimeter]
      /// [google.identity.accesscontextmanager.v1.ServicePerimeter].
      /// Referencing a nonexistent [AccessLevel]
      /// [google.identity.accesscontextmanager.v1.AccessLevel] will cause
      /// an error. If no [AccessLevel]
      /// [google.identity.accesscontextmanager.v1.AccessLevel] names are
      /// listed, resources within the perimeter can only be accessed via Google
      /// Cloud calls with request origins within the perimeter. Example:
      /// `accessPolicies/MY_POLICY/accessLevels/MY_LEVEL`. If a single `*` is
      /// specified for `access_level`, then all [IngressSources]
      /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressSource]
      /// will be allowed.
      case accessLevel(Swift.String)
      /// A Google Cloud resource that is allowed to ingress the perimeter.
      /// Requests from these resources will be allowed to access perimeter data.
      /// Currently only projects are allowed.
      /// Format: `projects/{project_number}`
      /// The project may be in any Google Cloud organization, not just the
      /// organization that the perimeter is defined in. `*` is not allowed, the
      /// case of allowing all Google Cloud resources only is not supported.
      case resource(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressSource"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the conditions under which an [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// matches a request. Conditions are based on information about the source of
  /// the request. The request must satisfy what is defined in `sources` AND
  /// identity related fields in order to match.
  public struct IngressFrom: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Sources that this [IngressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
    /// authorizes access from.
    public var sources: [ServicePerimeterConfig.IngressSource] = []

    /// A list of identities that are allowed access through this ingress
    /// policy. Should be in the format of email address. The email address
    /// should represent individual user or service account only.
    public var identities: [Swift.String] = []

    /// Specifies the type of identities that are allowed access from outside the
    /// perimeter. If left unspecified, then members of `identities` field will
    /// be allowed access.
    public var identityType: ServicePerimeterConfig.IdentityType =
      ServicePerimeterConfig.IdentityType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IngressFrom`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IngressFrom().with { $0.sources = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sources = CodingKeys(stringValue: "sources")
      static let identities = CodingKeys(stringValue: "identities")
      static let identityType = CodingKeys(stringValue: "identityType")

      static let _knownKeys: Set<Swift.String> = [
        "sources",
        "identities",
        "identityType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [ServicePerimeterConfig.IngressSource].self, forKey: .sources)
      {
        self.sources = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .identities) {
        self.identities = value
      }
      if let value = try container.decodeIfPresent(
        ServicePerimeterConfig.IdentityType.self, forKey: .identityType)
      {
        self.identityType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sources, forKey: .sources)
      try container.encode(self.identities, forKey: .identities)
      try container.encode(self.identityType, forKey: .identityType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressFrom"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the conditions under which an [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// matches a request. Conditions are based on information about the
  /// [ApiOperation]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
  /// intended to be performed on the target resource of the request. The request
  /// must satisfy what is defined in `operations` AND `resources` in order to
  /// match.
  public struct IngressTo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of [ApiOperations]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
    /// allowed to be performed by the sources specified in corresponding
    /// [IngressFrom]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressFrom]
    /// in this [ServicePerimeter]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeter].
    public var operations: [ServicePerimeterConfig.ApiOperation] = []

    /// A list of resources, currently only projects in the form
    /// `projects/<projectnumber>`, protected by this [ServicePerimeter]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeter] that are
    /// allowed to be accessed by sources defined in the corresponding
    /// [IngressFrom]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressFrom].
    /// If a single `*` is specified, then access to all resources inside the
    /// perimeter are allowed.
    public var resources: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IngressTo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IngressTo().with { $0.operations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let operations = CodingKeys(stringValue: "operations")
      static let resources = CodingKeys(stringValue: "resources")

      static let _knownKeys: Set<Swift.String> = [
        "operations",
        "resources",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [ServicePerimeterConfig.ApiOperation].self, forKey: .operations)
      {
        self.operations = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resources) {
        self.resources = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.operations, forKey: .operations)
      try container.encode(self.resources, forKey: .resources)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressTo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Policy for ingress into [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter].
  ///
  /// [IngressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// match requests based on `ingress_from` and `ingress_to` stanzas.  For an
  /// ingress policy to match, both the `ingress_from` and `ingress_to` stanzas
  /// must be matched. If an [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// matches a request, the request is allowed through the perimeter boundary
  /// from outside the perimeter.
  ///
  /// For example, access from the internet can be allowed either
  /// based on an [AccessLevel]
  /// [google.identity.accesscontextmanager.v1.AccessLevel] or, for traffic
  /// hosted on Google Cloud, the project of the source network. For access from
  /// private networks, using the project of the hosting network is required.
  ///
  /// Individual ingress policies can be limited by restricting which
  /// services and/or actions they match using the `ingress_to` field.
  public struct IngressPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Defines the conditions on the source of a request causing this
    /// [IngressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
    /// to apply.
    public var ingressFrom: ServicePerimeterConfig.IngressFrom? = nil

    /// Defines the conditions on the [ApiOperation]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
    /// and request destination that cause this [IngressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
    /// to apply.
    public var ingressTo: ServicePerimeterConfig.IngressTo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IngressPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IngressPolicy().with { $0.ingressFrom = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ingressFrom = CodingKeys(stringValue: "ingressFrom")
      static let ingressTo = CodingKeys(stringValue: "ingressTo")

      static let _knownKeys: Set<Swift.String> = [
        "ingressFrom",
        "ingressTo",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.ingressFrom = try container.decodeIfPresent(
        ServicePerimeterConfig.IngressFrom.self, forKey: .ingressFrom)
      self.ingressTo = try container.decodeIfPresent(
        ServicePerimeterConfig.IngressTo.self, forKey: .ingressTo)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.ingressFrom, forKey: .ingressFrom)
      try container.encodeIfPresent(self.ingressTo, forKey: .ingressTo)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the conditions under which an [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// matches a request. Conditions based on information about the source of the
  /// request. Note that if the destination of the request is also protected by a
  /// [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter], then that
  /// [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] must have
  /// an [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// which allows access in order for this request to succeed.
  public struct EgressFrom: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of identities that are allowed access through this [EgressPolicy].
    /// Should be in the format of email address. The email address should
    /// represent individual user or service account only.
    public var identities: [Swift.String] = []

    /// Specifies the type of identities that are allowed access to outside the
    /// perimeter. If left unspecified, then members of `identities` field will
    /// be allowed access.
    public var identityType: ServicePerimeterConfig.IdentityType =
      ServicePerimeterConfig.IdentityType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EgressFrom`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EgressFrom().with { $0.identities = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let identities = CodingKeys(stringValue: "identities")
      static let identityType = CodingKeys(stringValue: "identityType")

      static let _knownKeys: Set<Swift.String> = [
        "identities",
        "identityType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .identities) {
        self.identities = value
      }
      if let value = try container.decodeIfPresent(
        ServicePerimeterConfig.IdentityType.self, forKey: .identityType)
      {
        self.identityType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.identities, forKey: .identities)
      try container.encode(self.identityType, forKey: .identityType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressFrom"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the conditions under which an [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// matches a request. Conditions are based on information about the
  /// [ApiOperation]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
  /// intended to be performed on the `resources` specified. Note that if the
  /// destination of the request is also protected by a [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter], then that
  /// [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] must have
  /// an [IngressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressPolicy]
  /// which allows access in order for this request to succeed. The request must
  /// match `operations` AND `resources` fields in order to be allowed egress out
  /// of the perimeter.
  public struct EgressTo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of resources, currently only projects in the form
    /// `projects/<projectnumber>`, that are allowed to be accessed by sources
    /// defined in the corresponding [EgressFrom]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressFrom].
    /// A request matches if it contains a resource in this list.  If `*` is
    /// specified for `resources`, then this [EgressTo]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressTo]
    /// rule will authorize access to all resources outside the perimeter.
    public var resources: [Swift.String] = []

    /// A list of [ApiOperations]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
    /// allowed to be performed by the sources specified in the corresponding
    /// [EgressFrom]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressFrom].
    /// A request matches if it uses an operation/service in this list.
    public var operations: [ServicePerimeterConfig.ApiOperation] = []

    /// A list of external resources that are allowed to be accessed. Only AWS
    /// and Azure resources are supported. For Amazon S3, the supported format is
    /// s3://BUCKET_NAME. For Azure Storage, the supported format is
    /// azure://myaccount.blob.core.windows.net/CONTAINER_NAME. A request matches
    /// if it contains an external resource in this list (Example:
    /// s3://bucket/path). Currently '*' is not allowed.
    public var externalResources: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EgressTo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EgressTo().with { $0.resources = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resources = CodingKeys(stringValue: "resources")
      static let operations = CodingKeys(stringValue: "operations")
      static let externalResources = CodingKeys(stringValue: "externalResources")

      static let _knownKeys: Set<Swift.String> = [
        "resources",
        "operations",
        "externalResources",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resources) {
        self.resources = value
      }
      if let value = try container.decodeIfPresent(
        [ServicePerimeterConfig.ApiOperation].self, forKey: .operations)
      {
        self.operations = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .externalResources)
      {
        self.externalResources = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resources, forKey: .resources)
      try container.encode(self.operations, forKey: .operations)
      try container.encode(self.externalResources, forKey: .externalResources)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressTo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Policy for egress from perimeter.
  ///
  /// [EgressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// match requests based on `egress_from` and `egress_to` stanzas.  For an
  /// [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// to match, both `egress_from` and `egress_to` stanzas must be matched. If an
  /// [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// matches a request, the request is allowed to span the [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] boundary.
  /// For example, an [EgressPolicy]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// can be used to allow VMs on networks within the [ServicePerimeter]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeter] to access a
  /// defined set of projects outside the perimeter in certain contexts (e.g. to
  /// read data from a Cloud Storage bucket or query against a BigQuery dataset).
  ///
  /// [EgressPolicies]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
  /// are concerned with the *resources* that a request relates as well as the
  /// API services and API actions being used.  They do not related to the
  /// direction of data movement.  More detailed documentation for this concept
  /// can be found in the descriptions of [EgressFrom]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressFrom]
  /// and [EgressTo]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressTo].
  public struct EgressPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Defines conditions on the source of a request causing this [EgressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
    /// to apply.
    public var egressFrom: ServicePerimeterConfig.EgressFrom? = nil

    /// Defines the conditions on the [ApiOperation]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.ApiOperation]
    /// and destination resources that cause this [EgressPolicy]
    /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy]
    /// to apply.
    public var egressTo: ServicePerimeterConfig.EgressTo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EgressPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EgressPolicy().with { $0.egressFrom = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let egressFrom = CodingKeys(stringValue: "egressFrom")
      static let egressTo = CodingKeys(stringValue: "egressTo")

      static let _knownKeys: Set<Swift.String> = [
        "egressFrom",
        "egressTo",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.egressFrom = try container.decodeIfPresent(
        ServicePerimeterConfig.EgressFrom.self, forKey: .egressFrom)
      self.egressTo = try container.decodeIfPresent(
        ServicePerimeterConfig.EgressTo.self, forKey: .egressTo)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.egressFrom, forKey: .egressFrom)
      try container.encodeIfPresent(self.egressTo, forKey: .egressTo)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Specifies the types of identities that are allowed access in either
  /// [IngressFrom]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.IngressFrom]
  /// or [EgressFrom]
  /// [google.identity.accesscontextmanager.v1.ServicePerimeterConfig.EgressFrom]
  /// rules.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum IdentityType: Codable, Equatable, Sendable {
    /// No blanket identity group specified.
    case unspecified
    /// Authorize access from all identities outside the perimeter.
    case anyIdentity
    /// Authorize access from all human users outside the perimeter.
    case anyUserAccount
    /// Authorize access from all service accounts outside the perimeter.
    case anyServiceAccount
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .anyIdentity: return 1
      case .anyUserAccount: return 2
      case .anyServiceAccount: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IDENTITY_TYPE_UNSPECIFIED"
      case .anyIdentity: return "ANY_IDENTITY"
      case .anyUserAccount: return "ANY_USER_ACCOUNT"
      case .anyServiceAccount: return "ANY_SERVICE_ACCOUNT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IdentityType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IDENTITY_TYPE_UNSPECIFIED": self = .unspecified
      case "ANY_IDENTITY": self = .anyIdentity
      case "ANY_USER_ACCOUNT": self = .anyUserAccount
      case "ANY_SERVICE_ACCOUNT": self = .anyServiceAccount
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IdentityType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .anyIdentity
      case 2: self = .anyUserAccount
      case 3: self = .anyServiceAccount
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("IDENTITY_TYPE_UNSPECIFIED")
      case .anyIdentity: return try container.encode("ANY_IDENTITY")
      case .anyUserAccount: return try container.encode("ANY_USER_ACCOUNT")
      case .anyServiceAccount: return try container.encode("ANY_SERVICE_ACCOUNT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.identity.accesscontextmanager.v1.ServicePerimeterConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
